version: '3.8'

services:
  api-faculdade:
    build: .
    container_name: api-faculdade
    restart: always
    environment:
      - MONGODB_CONNECTION_URI=mongodb://mongodb:27017
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - mongodb
    command: ["fastapi", "dev", "main.py"]

  mongodb:
    image: mongo:6.0  # ou a versão que preferir
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor

volumes:
  mongo_data:
